- README.md
- scripts/strava_auth.py
It took me some time to figure out how to get the access token so I added the instructions. Please check if you want to pull them.
> Add script and instructions to obtain Strava API token

- README.md
- cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
- cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
- zwift_offline.py
Fixes issue #37 for profiles created using zoffline
> Update to Zwift 1.0.48307

- README.md
- cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
- cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
- cdn/static/web/launcher/embed-noauto.html
- zwift_offline.py
* Fix issues with Mac launcher 1.0.23 (issue #27)
* Update instructions to configure Mac client
* Fix issues with Windows launcher 1.0.50
* Add support for multiple profiles (tested with Windows and Mac, untested with Docker)
* Remove free trial limit from profile (mentioned in issue #25)
* Add Garmin Connect activity upload
* Fix multi profile on Android (issue #44)
* Update to Zwift 1.0.48969
> Various commits

- cdn/static/web/launcher/embed-noauto.html
- zwift_offline.py
Workaround for Windows client crash at foot of Alpe du Zwift (issue #38)
Sorry, I'm not used to Github. I made a few edits in my fork before this one, then I made it even with zoffline/master to create a pull request with only this change, but all previous commits appear in the pull request. Can you squash it?
> Workaround for Windows client crash

- zwift_offline.py
> Fix ANSI color in Windows 10

- README.md
- cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
- cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
- zwift_offline.py
> Update to Zwift 1.0.49751

- README.md
- cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
- cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
- standalone.py
Also a fix for Python 3 (please check)
> Update to Zwift 1.0.49777

- README.md
- protobuf/profile.proto
- protobuf/tcp-node-msgs.proto
- protobuf/udp-node-msgs.proto
- standalone.py
- zwift_offline.py
Please see #56 for more details.
There are changes to profile, tcp-node-msgs and udp-node-msgs proto files, I didn't add the .py files because my compiler generates files with many differences. If you decide to merge this, please update these files.
> Add ghosts feature

- README.md
- standalone.py
- start_lines.csv
Suggested by @msobecki in https://github.com/zoffline/zwift-offline/issues/56#issuecomment-643440034
> Add start line option for ghosts

- standalone.py
- zwift_offline.py
> Encode activity name for urlopen

- README.md
- standalone.py
Organize ghosts in `course/roadID` directory structure and load automatically (copying to load folder is not required).
> Organize and auto load ghosts

- scripts/get_profile.spec
- scripts/strava_auth.spec
- standalone.spec
Not sure if it's related but this built clean files on VirusTotal analysis
https://www.virustotal.com/gui/file/f63e83e13d7cb0b6814a0c7742f180a2098c4f112f592bc4d9e21afdfd276aef/detection
https://www.virustotal.com/gui/file/e37a9b0193c75a29f67d2399baf3ab25411804e103b8b8376eea3411f36f3b1a/detection
https://www.virustotal.com/gui/file/b6680fe3bf3433613a9f1100bcfa090cd48d02beb12c9e57d0b44a3920a86d25/detection
> Sign Windows executables

- scripts/get_profile.py
Added except clause for invalid uname/pass to exit gracefully
Cleaned up a bit for pythonic conformance
resolves issue #101
>     Addressed get_profile() hanging issue for incompatible OSes

- zwift_offline.py
linux created text file has only \n
> support for linux/mac created garmin textfile

- README.md
- standalone.py
- zwift_offline.py
Not sure if you want to merge this, so opening pull request.
> Add Discord bot

- scripts/upload_activity.py
- zwift_offline.py
> Add upload_activity

- zwift_offline.py
Fixes support for iOS Companion app by returning JSON responses as 'application/json' and responding to partner auth calls.
> Improve iOS support with ZCA

- variants.txt
Fixes Zwift crashes on MacOS after the 1.31 update
> Fix: add new request type to variants

- zwift_offline.py
I added missing sqlalchemy text sanitizations. They were failing for me in the docker container based on python 3.10 as mentioned in https://github.com/zoffline/zwift-offline/issues/211
This one seems to work again.
> ADD: Fix text sanitization for sql

- README.md
- cdn/gameassets/Zwift_Updates_Root/ZwiftMac_ver_cur.xml
- cdn/gameassets/Zwift_Updates_Root/Zwift_ver_cur.xml
- zwift_offline.py
Add Scotland events
Fix get_partial_profile for ghosts
Still need to update variants.txt and game_info.txt
> Update to Zwift 1.0.107342

- README.md
Describes Fix for #215 in the readme
> Fix: Readme for MacOS installation

- standalone.py
Pop() is described as random. So in this way, the bots.txt naming is exhausted and starts again if more bots exist than names.
> Pop bots from list

- variants.txt
Enable Apple silicon support
#269
> Enable Apple silicon support

- README.md
> Update ZCA patching instructions

- README.md
- scripts/find_equip.py
- scripts/get_pro_names.py
```
[user@personal zwift-offline]$ scripts/find_equip.py -p emonda -s sworks -o blue -j zwift -e kask
{
"ride_jersey": 1576116423,
"ride_jersey_name": "Zwift Academy Finalist",
"ride_helmet_type": 857849616,
"ride_helmet_type_name": "Kask Elemento",
"ride_socks_type": 1104470558,
"ride_socks_name": "Dotted Blue",
"ride_shoes_type": 1614109799,
"ride_shoes_type_name": "Sworks SP7",
"bike_frame_colour": 3812628067633856512,
"bike_frame_colour_name": "Trek Emonda-Emonda SLR",
"bike_frame": 142926447,
"bike_frame_name": "Trek Emonda"
}
```
Quick script to find singular matches from game dictionary
> Add find_equip.py

- README.md
- standalone.py
> Add option to disable proxy

- README.md
> Mention Intervals.icu upload in README

- zwift_offline.py
Allows to override features by creating a variants.txt file in the profile directory. For Windows release and Docker users (addresses #365).
> Add features overriding

- requirements.txt
> Bump gevent from 24.2.1 to 25.5.1
